storyblok.webhook:
    path: /webhook/{urlSecret}
    controller: Torr\Storyblok\Webhook\Controller\WebhookController::webhook
    defaults:
        urlSecret: ~

storyblok.asset-proxy:
    path: /asset/{path}
    controller: Torr\Storyblok\Assets\Controller\AssetProxyController::proxyAsset
    requirements:
        path: .+?
